### ISSUE TITLE
Unexpected behaviour due to go 1.23 `time.Timer` updates

### ISSUE THREAD

**Issue by timohahaa** [sasha-s/go-deadlock#38]
Hello!
We have a service, that is using your library to detect potential deadlocks.
Service is using go 1.22 (a `go 1.22.0` directive inside a `go.mod` file).
This service is deployed via a CI/CD pipeline where it is build inside a docker container.
We have recently upgraded go version in this docker-builder image from 1.22.0 to 1.23.0 and now our service is constantly stopping mid-work due to `POTENTIAL DEADLOCK` warning.

Note:
- service code HAS NOT CHANGED as well as the version of this library, that we are using
- service go version is declared as 1.22.0 inside `go.mod` file and HAS NOT CHANGED
- go version inside docker container HAS CHANGED from 1.22.0 to 1.23.0 and now the service is giving deadlock warnings.

What could be the issue here? Maybe something inside a go runtime has changed that "breaks" this library?

**Comment by timohahaa** [comment]
I think the issue might be related to recent change in how `time.Timer` and `time.Ticker` work. Their behaviour was changed in go 1.23.0 (see here - https://go.dev/doc/go1.23#timer-changes), and your library relies on timers to work.

**Comment by sasha-s** [comment]
Thank you for reporting this. 
I will look at what could be going on. 
In a meanwhile, if you have a reproduction (minimal, synthetic example). it would be very helpful.

**Comment by linkdata** [comment]
You could try https://github.com/linkdata/deadlock
That implementation doesn't use a pool of timers, which may or may not make a difference.

**Comment by sheo9000** [comment]
> Thank you for reporting this. I will look at what could be going on. In a meanwhile, if you have a reproduction (minimal, synthetic example). it would be very helpful.

Having the same issue here, here is the reproduction
```go
package main

import (
	"fmt"
	"time"

	"github.com/sasha-s/go-deadlock"
)

var lock1 deadlock.RWMutex
var lock2 deadlock.RWMutex

func main() {
	deadlock.Opts.DeadlockTimeout = 2500 * time.Millisecond

	tStart := time.Now()

	for i := 1; i <= 500; i++ {
		go func() {
			lock1.RLock()
			time.Sleep(1 * time.Second)
			lock2.RLock()
			time.Sleep(1 * time.Second)
			lock2.RUnlock()
			lock1.RUnlock()
		}()
	}
	tLock := time.Now()
	lock1.Lock()
	fmt.Printf("locked in: %v\n", time.Since(tLock))
	time.Sleep(1 * time.Second)
	lock1.Unlock()

	fmt.Printf("end: %v\n", time.Since(tStart))
}
```
Output
```
locked in: 2.00134499s
POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 1 lock 0x5ac1e0
main.go:29 main.main { lock1.Lock() } <<<<<
~/go/pkg/mod/github.com/sasha-s/go-deadlock@v0.3.5/deadlock.go:119 go-deadlock.(*RWMutex).Lock { func (m *RWMutex) Lock() { }
/usr/local/go/src/internal/runtime/atomic/types.go:193 atomic.(*Uint32).Load { func (u *Uint32) Load() uint32 { }

Have been trying to lock it again for more than 2.5s
goroutine 1046 lock 0x5ac1e0
main.go:20 main.main.func1 { lock1.RLock() } <<<<<
~/go/pkg/mod/github.com/sasha-s/go-deadlock@v0.3.5/deadlock.go:140 go-deadlock.(*RWMutex).RLock { func (m *RWMutex) RLock() { }

Here is what goroutine 1 doing now
goroutine 1 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/local/go/src/runtime/time.go:285 +0xf2
main.main()
	/home/shamweri/yadisk/other/script/test/tost/main.go:31 +0x138

exit status 2
```
With default `sync` package the output is this
```
locked in: 2.001065408s
end: 3.001981134s
```

**Comment by sasha-s** [comment]
Also, gave you tried running it with [GODEBUG setting](https://go.dev/doc/godebug) [asynctimerchan=1](https://go.dev/pkg/time/#NewTimer)?
It might confirm what’s causing the problem.

**Comment by ChrisMcD1** [comment]
I just ran the master branch of lazygit with go `1.23.6` with `go run main.go -debug`:
```
godebug (
	default=go1.22
	asynctimerchan=1
)
```
inside of `go.mod`, and still received `POTENTIAL DEADLOCK: Recursive locking:` warnings. 
Running `go1.22.0 run main.go -debug` did not have the errors.

Sorry that I don't have a more minimal reproducible example to provide!

**Comment by ChrisMcD1** [comment]
My apologies, our problem was because we were on version `v0.3.1` of this library, which included a version of `goid` prior to their support for go 1.23. This manifested itself as _every goroutine_ having a goid of `2`, so anytime any two goroutines tried to lock a mutex at the same time, it thought that it was a recursive lock. Bumping to version `v0.3.5`, and therefore the newer `goid` resolved the issue!

@timohahaa Can you verify which version of `go-deadlock` you were having the issue with?
